Import Libraries

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

Load Dataset

In [3]:
df = pd.read_csv('../data/raw/malaysia_house_price_data_2025.csv')
df.head()

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,Tasek Gelugor,Penang,Freehold,Terrace House,331800.0,304.0,593
1,BANDAR PUTRA,Kulai,Johor,Freehold,"Cluster House, Terrace House",590900.0,322.0,519
2,TAMAN LAGENDA TROPIKA TAPAH,Chenderiang,Perak,Freehold,Terrace House,229954.0,130.0,414
3,SCIENTEX JASIN MUTIARA,Bemban,Melaka,Freehold,Terrace House,255600.0,218.0,391
4,TAMAN LAGENDA AMAN,Tapah,Perak,Leasehold,Terrace House,219300.0,168.0,363

Checking Tenure for Mixed Values is important or not?

In [4]:
print(df["Tenure"].value_counts())

Tenure
Freehold               1318
Leasehold               624
Freehold, Leasehold      31
Leasehold, Freehold      27
Name: count, dtype: int64

In [5]:
mixed = df[df["Tenure"].str.contains(",")]

print(mixed.shape)
mixed.head(10)

(58, 8)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
30,BANDAR BARU KANGKAR PULAI,Kulai,Johor,"Freehold, Leasehold","Cluster House, Terrace House",553200.0,297.0,155
106,BANDAR BARU UDA,Johor Bahru,Johor,"Leasehold, Freehold",Terrace House,500000.0,279.0,78
146,BANDAR SERI BOTANI,Ipoh,Perak,"Freehold, Leasehold","Terrace House, Semi D",496800.0,344.0,67
171,TAMAN SAMARINDAH,Kota Samarahan,Sarawak,"Freehold, Leasehold",Terrace House,300000.0,168.0,59
201,KUALA BERANG,Hulu Terengganu,Terengganu,"Freehold, Leasehold","Bungalow, Terrace House",200000.0,62.0,53
232,TAMAN CEMPAKA,Ipoh,Perak,"Freehold, Leasehold",Terrace House,199000.0,202.0,49
236,KEPONG BARU,Kepong,Kuala Lumpur,"Leasehold, Freehold",Terrace House,667500.0,445.0,48
274,TAMAN BUKIT DAHLIA,Pasir Gudang,Johor,"Freehold, Leasehold",Terrace House,480000.0,353.0,43
297,BANDAR SERI BOTANI,Simpang Pulai,Perak,"Freehold, Leasehold",Terrace House,448800.0,288.0,40
300,TAMAN CANNING,Ipoh,Perak,"Freehold, Leasehold","Terrace House, Semi D, Bungalow",425000.0,171.0,39

In [8]:
mixed = df[df["Tenure"].str.contains(",")]

print(mixed["Type"].value_counts())

Type
Terrace House                      39
Bungalow, Terrace House             3
Semi D, Terrace House               3
Terrace House, Semi D               2
Terrace House, Bungalow             2
Cluster House, Terrace House        1
Terrace House, Semi D, Bungalow     1
Service Residence                   1
Terrace House, Town House           1
Apartment                           1
Town House, Bungalow                1
Cluster House                       1
Terrace House, Cluster House        1
Bungalow, Semi D                    1
Name: count, dtype: int64

In [6]:
print(mixed["State"].value_counts())

State
Selangor           16
Johor              10
Perak              10
Melaka              7
Sarawak             4
Terengganu          3
Negeri Sembilan     3
Kuala Lumpur        2
Pahang              2
Penang              1
Name: count, dtype: int64

In [7]:
print(mixed["Area"].value_counts())

Area
Ipoh                                 6
Skudai                               3
Puchong                              3
Johor Bahru                          2
Kerteh                               2
Petaling Jaya                        2
Dengkil                              2
Kuching                              2
Bertam                               2
Kulai                                1
Kota Samarahan                       1
Hulu Terengganu                      1
Kepong                               1
Pasir Gudang                         1
Simpang Pulai                        1
Jalan Klang Lama (Old Klang Road)    1
Bukit Rambai                         1
Balai Panjang                        1
Klang                                1
Butterworth                          1
Bidor                                1
Pengerang                            1
Sungai Buloh                         1
Kuantan                              1
Parit Buntar                         1
Seri Kembangan                       1
Telok Kemang                         1
Kajang                               1
Banting                              1
Teluk Intan                          1
Shah Alam                            1
Tanjong Duabelas                     1
Pekan                                1
Batu Berendam                        1
Masai                                1
Bukit Baru                           1
Rantau                               1
Cheras                               1
Duyong                               1
Sri Aman                             1
Sikamat                              1
Kapar                                1
Tebrau                               1
Name: count, dtype: int64

## Clean Tenure

Combine **Freehold, Leasehold** and **Leasehold, Freehold** into **Freehold and Leasehold** as they represent the same tenure type.

In [9]:
df["Tenure"] = df["Tenure"].replace({
    "Freehold, Leasehold": "Freehold and Leasehold",
    "Leasehold, Freehold": "Freehold and Leasehold",
})

Verify the changes

In [10]:
print(df["Tenure"].value_counts())

Tenure
Freehold                  1318
Leasehold                  624
Freehold and Leasehold      58
Name: count, dtype: int64